[Application]
name = "demon_pear"
prefix = "dp"
home = "dashboard"
description = "This application provides for monitoring and notification of network devices."
version = "0.0.1"
environment = "development"
releaseDate = "2021-07-01"
copyright = "2021"
author = "Cervical Hamster"
license= "MIT"
locale = "en_GB"

[Database]
version = 1
type = "storm"
host = ""
port = 0
name = ""
user = ""
pass = ""
path = ""
poolsize = 0
timeout = 0

[Server]
host = "127.0.0.1"
port = 5052
protocol = "http"
environment = "development"

[Translation]
locale = "en_GB"
host = "10.147.20.105"
port = 5050
protocol = "http"

[Translation.Permitted]
[[Translation.Permitted.Origins]]
name = "demon_pear"
[[Translation.Permitted.Origins]]
name = "trnsl8r_connect"
[[Translation.Permitted.Origins]]
name = "cosmic-orange"
[[Translation.Permitted.Origins]]
name = "frantic-aegis"
[[Translation.Permitted.Origins]]
name = "frantic-core"
[[Translation.Permitted.Origins]]
name = "frantic-template"


[[Translation.Permitted.Locales]]
key = "jp_JP"
name = "Japanese (Japan)"
[[Translation.Permitted.Locales]]
key = "fr_FR"
name = "French (France)"
[[Translation.Permitted.Locales]]
key = "de_DE"
name = "German (Germany)"
[[Translation.Permitted.Locales]]
key = "pl_PL"
name = "Polish (Poland)"
[[Translation.Permitted.Locales]]
key = "es_ES"
name = "Spanish (Spain)"

[Assets]
logo = "co-logo.png"
favicon = "co-favicon.ico"

[Dates]
[Dates.Formats]
dateTime = "2006-01-02 15:04:05"
date = "02/01/2006"
time = "15:04:05"
backup = "060102"
backupFolder = "060102150405"
human = "02 Jan 2006"
dmy2 = "02/01/06"
ymd = "2006-01-02"
internal = "20060102"

[History]
maxEntries = 10


[[Hosts]]
name = "SILICON"
fqdn = "silicon.local"
ip = "192.168.1.145"
zone = "local"

[[Hosts]]
name = "PROTEUS"
fqdn = "proteus.local"
ip = "10.147.20.104"
zone = "zero"

[[Hosts]]
name = "UNREACHABLE"
fqdn = "unreachable.any"
ip = "192.192.192.192"
zone = "any"

[[Hosts]]
name = "HPDeskJet"
fqdn = "hp6c02e0332032.local."
ip = "192.168.1.150"
zone = "local"

[[Hosts]]
name = "EUROPA"
fqdn = "europa.local"
ip = "192.168.1.103"
zone = "local"

[[Hosts]]
name = "MERCURY"
fqdn = "mercury.zero"
ip = "10.147.20.106"
zone = "zero"

[[Hosts]]
name = "HELIOS"
fqdn = "helios.zero"
ip = "10.147.20.110"
zone = "zero"

[[Hosts]]
name = "ORION"
fqdn = "orion.zero"
ip = "10.147.20.229"
zone = "zero"

[[Hosts]]
name = "FATHER"
fqdn = "father.zero"
ip = "10.147.20.221"
zone = "zero"

[[Hosts]]
name = "pdp1173"
fqdn = "pdp1173.com"
ip = "pdp1173.com"
zone = "external"

[Security]
[Security.Sessions]
expiryPeriod = 10 # expiry period in minutes

[Security.Sessions.Keys]
session = "xs-id"
userKey = "xs-uid"
userCode = "xs-ucode"
token = "xs-token"
expiryPeriod = "xs-expiry"
locale = "xs-locale"
theme = "xs-theme"
timezone = "xs-tz"
role = "xs-role"

[Security.Service]
userUID = "sys"
userName = "service"

[Message]
[Message.Keys]
type = "xm-type"
title = "xm-title"
content = "xm-content"
action = "xm-act"

[Display]
delim = "⋮"

[Status]
unknown = "UNKN"
online = "ONLN"
offline = "OFLN"
error = "ERRO"
warning = "WARN"



[Communications]

[Communications.Pushover]
UserKey = "uyosdopsu9wxxo7b264bmnnhbfz8nj"
APIToken = "awrpfi2kbfa8wx7csjmf82whenrbhw"

[Communications.Email]
host = "smtp.gmail.com"
port = 587
user = "user@test.com"
password = "password"
from = "user2@test.com"
footer = "This is a footer"
admin = "babs@babs.com"

[Logging]
[Logging.Disable]
general = "false"
timing = "false"
service = "false"
audit = "false"
translation = "false"
trace = "false"
warning = "false"
event = "false"
security = "false"
database = "false"
api = "false"
import = "false"
export = "false"
comms = "false"
all = ""

[Logging.Defaults]
maxSize = "10"
maxBackups = "10"
maxAge = "10"
compress = "true"

[Backups]
retainDays=7