---
services:
  trnsl8r_service:
    image: mt1976/trnsl8r_server:latest
    container_name: trnsl8r_server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /Users/matttownsend/Docker/trnsl8r_service/backups:/app/data/backups
      - /Users/matttownsend/Docker/shared/database:/app/data/database
      - /Users/matttownsend/Docker/trnsl8r_service/dumps:/app/data/dumps
      - /Users/matttownsend/Docker/shared/logs:/app/data/logs
      - /Users/matttownsend/Docker/trnsl8r_service/defaults:/app/data/defaults
    ports:
      - 5055:8080
    restart: unless-stopped
