---
services:
  trnsl8r_service:
    image: mt1976/trnsl8r_server:latest
    container_name: trnsl8r_server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /Volumes/External HD/Docker/Shared/backups/trnsl8r_service:/data/backups
      - /Volumes/External HD/Docker/Shared/database:/data/database
      - /Volumes/External HD/Docker/Shared/dumps/trnsl8r_service:/data/dumps
      - /Volumes/External HD/Docker/Shared/logs:/data/logs
      - /Volumes/External HD/Docker/Shared/defaults:/data/defaults
    ports:
      - 5050:5050
    restart: unless-stopped
